table Sales
	lineageTag: 135c03b5-ea12-4df4-b8c4-6592412bb53a

	column Region
		dataType: string
		lineageTag: f027c27f-3c68-4167-b70d-dfb6073611a4
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 031fac66-2f66-42a8-95f0-194d6a3e2682
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: int64
		formatString: 0
		lineageTag: cb02bfac-f91a-4654-a88a-202aaf6dc558
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8ssvKslQ0lHySSwoyS8AMkwNgEApVidaKTi/FFXKxAgmBdPlm19anAqkLdD1wCTMTKESronFJchmGVuCtcQCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Region = _t, Product = _t, Sales = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Region", type text}, {"Product", type text}, {"Sales", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

